language: python
before_script: # configure a headless display to test plot generation
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=snoohelper snoohelper_tests.py
after_success:
  coveralls